sudo: false

language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

env:
  matrix:
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=3.0.*
  global:
    - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - composer selfupdate
  - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}

script:
  - ./vendor/bin/phpunit
