sudo: false

language: php

php:
  - 7.2

env:
  matrix:
    - SYMFONY_VERSION=4.0.*
    - SYMFONY_VERSION=5.0.*
  global:
    - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_script:
  - composer selfupdate
  - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}

script:
  - ./vendor/bin/phpunit
