services:
  statistico.driver.redis:
    class: Fieg\Statistico\Driver\RedisDriver
    arguments:
      - # gets replaced in extension

  statistico:
    class: Fieg\Statistico\Statistico
    arguments:
      - '@statistico.driver.redis'

  statistico.reader:
    class: Fieg\Statistico\Reader
    arguments:
      - '@statistico.driver.redis'

  statistico.command.buckets:
    class: Fieg\StatisticoBundle\Command\BucketsCommand
    arguments:
      - '@statistico.reader'
    tags:
      - { name: 'console.command' }

  statistico.command.graph:
    class: Fieg\StatisticoBundle\Command\GraphCommand
    arguments:
      - '@statistico.reader'
    tags:
      - { name: 'console.command' }
