services:
  statistico.driver.redis:
    class: Fieg\Statistico\Driver\RedisDriver
    arguments:
      - # gets replaced in extension

  statistico:
    class: Fieg\Statistico\Statistico
    arguments:
      - @statistico.driver.redis

  statistico.reader:
    class: Fieg\Statistico\Reader
    arguments:
      - '@statistico.driver.redis'
